### ISSUE TITLE
java.lang.NullPointerException: Exception in server tick loop

### ISSUE THREAD

**Issue by camle2145** [Earthcomputer/SecureSeed#3] opened 2021-05-06 19:31 UTC
No idea what caused this outside of the mod so forgive me if it's super obvious, but I got this crash report on startup:
```
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 5/6/21 3:24 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at java.lang.System.arraycopy(Native Method)
	at net.earthcomputer.secureseed.Globals.setupGlobals(Globals.java:41)
	at net.minecraft.class_3218.localvar$zgf000$onInitServerWorld(class_3218.java:3051)
	at net.minecraft.class_3218.<init>(class_3218.java:190)
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:368)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:335)
	at net.minecraft.class_3176.method_3823(class_3176.java:179)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:645)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 4.15.0-124-generic
	Java Version: 1.8.0_282, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 588559176 bytes (561 MB) / 1301282816 bytes (1241 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 2
	JVM Flags: 2 total; -Xms128M -Xmx4096M
	Fabric Mods: 
		carpet: Carpet Mod 1.4.35
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		com_github_ben-manes_caffeine_caffeine: caffeine 2.8.0
		com_graphql-java_graphql-java: graphql-java 16.1
		com_graphql-java_java-dataloader: java-dataloader 2.2.3
		com_zaxxer_hikaricp: HikariCP 3.4.2
		deltalogger: DeltaLogger 1.1.3
		fabric: Fabric API 0.34.1+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.2+d6244c6d7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabricloader: Fabric Loader 0.11.3
		fastfurnace: FastFurnace 2.4
		fiblib: FibLib 1.0.2
		golfiv: Golf IV 0.3.1
		invview: InvView 1.4.1-1.16.4+
		io_leangen_geantyref_geantyref: geantyref 1.3.7
		java: OpenJDK 64-Bit Server VM 8
		krypton: Krypton 0.1.2
		luckperms: LuckPerms 5.3.9
		minecraft: Minecraft 1.16.5
		mysql_mysql-connector-java: mysql-connector-java 8.0.19
		org_antlr_antlr4-runtime: antlr4-runtime 4.7.2
		org_jdbi_jdbi3-core: jdbi3-core 3.12.2
		org_jdbi_jdbi3-sqlite: jdbi3-sqlite 3.12.2
		org_reactivestreams_reactive-streams: reactive-streams 1.0.3
		org_slf4j_slf4j-api: slf4j-api 1.8.0-beta4
		org_xerial_sqlite-jdbc: sqlite-jdbc 3.32.3.2
		packet_tweaker: Packet Tweaker 0.1.1
		sax: Simple Anti X-Ray 1.1.0
		secureseed: SecureSeed 0.1
		server_translations_api: Server Translations API 1.4.0
		serversimplified: Server Simplified 1.2.2
		starlight: Starlight fabric-1.0.0-RC2-82ae5ca
	Player Count: 0 / 20; []
	Data Packs: vanilla, Fabric Mods
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

**Comment by Earthcomputer** [comment] 2021-05-06 19:35
Duplicate of #1

**Closed as completed by Earthcomputer** 2021-05-06 19:35 UTC
